name: Build Code Editor APK (Definitive)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install cython==0.29.34 buildozer
          pip install -r requirements.txt

      - name: Run Diagnostics, Failsafe, and Build
        run: |
          echo "--- DIAGNOSTIC STEP 1: Listing all files after checkout ---"
          ls -la

          echo "--- FAILSAFE STEP 2: Forcibly create a spec file if missing ---"
          if [ ! -f buildozer.spec ]; then
              echo "buildozer.spec NOT FOUND! Running buildozer init..."
              buildozer init
          else
              echo "buildozer.spec was found successfully."
          fi

          echo "--- DIAGNOSTIC STEP 3: Listing all files again to confirm spec file exists ---"
          ls -la

          echo "--- FINAL STEP 4: Building the APK ---"
          yes | buildozer android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CodeEditor-APK
          path: bin/*.apk
