name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install cython==0.29.34 buildozer
          pip install -r requirements.txt

      - name: Build with Buildozer
        run: |
          yes | buildozer android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CodeEditor-APK
          path: bin/*.apk
