name: Build Code Editor APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install cython==0.29.34 buildozer
          pip install -r requirements.txt

      - name: Build the APK
        run: |
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CodeEditor-APK
          path: bin/*.apk
```*(Self-correction: I've removed the `buildozer.spec` file from this list. It is not strictly necessary as Buildozer can run with default settings which are sufficient for this build, and it removes one more potential point of failure.)*
